// <auto-generated />
using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: AssemblyTitle ("CxSoftware.RutSharp")]
[assembly: AssemblyDescription ("")]
[assembly: AssemblyConfiguration ("")]
[assembly: AssemblyCompany ("CxSoftware Ltda.")]
[assembly: AssemblyProduct ("")]
[assembly: AssemblyCopyright ("")]
[assembly: AssemblyTrademark ("")]
[assembly: AssemblyCulture ("")]
[assembly: AssemblyVersion ("1.0.*")]

